name: lotto_lee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: ^0.19.0
  http: ^1.2.2
  html: ^0.15.4
  
  # Firebase packages
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_analytics: ^10.8.5
  firebase_storage: ^11.6.5
  
  # State management & utilities
  provider: ^6.1.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  
  # UI packages
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700